build_job:
  stage: build
  tags:
    - mylongtag
  script:
    - mkdir build
    - cd build
    - cmake .. -DJOB_ID=$CI_JOB_ID
    - make

test_job:
  stage: build
  tags:
    - mylongtag
  script:
    - $CI_PROJECT_DIR/build/bin/hello_world_1
    - $CI_PROJECT_DIR/build/bin/hello_world_2
    - $CI_PROJECT_DIR/build/bin/hello_world_3
